source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'pg'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form'
gem 'slim-rails'
gem 'draper'
gem 'devise'

group :development do
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'pry-rails'
  gem 'bullet'
  gem 'traceroute'
  gem 'letter_opener'
end

gem 'faker'
gem 'bugsnag'

group :production do
  gem 'rails_12factor'
end
