default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres

development:
  <<: *default
  database: pancakes_development
  password:

test:
  <<: *default
  database: pancakes_test

production:
  <<: *default
  database: pancakes_production
